export const BIKE_ACTION_TYPE = {
	SET_FETCH_BIKE_STATIONS_START: 'bike/SET_FETCH_BIKE_STATIONS_START',
	SET_FETCH_BIKE_STATIONS_SUCCESS: 'bike/SET_FETCH_BIKE_STATIONS_SUCCESS',
	SET_FETCH_BIKE_STATIONS_FAILURE: 'bike/SET_FETCH_BIKE_STATIONS_FAILURE',
	SET_FETCH_BIKE_AVAILABILITY_START: 'bike/SET_FETCH_BIKE_AVAILABILITY_START',
	SET_FETCH_BIKE_AVAILABILITY_SUCCESS: 'bike/SET_FETCH_BIKE_AVAILABILITY_SUCCESS',
	SET_FETCH_BIKE_AVAILABILITY_FAILURE: 'bike/SET_FETCH_BIKE_AVAILABILITY_FAILURE',
	SET_FETCH_BIKE_LANES_START: 'bike/SET_FETCH_BIKE_LANES_START',
	SET_FETCH_BIKE_LANES_SUCCESS: 'bike/SET_FETCH_BIKE_LANES_SUCCESS',
	SET_FETCH_BIKE_LANES_FAILURE: 'bike/SET_FETCH_BIKE_LANES_FAILURE',
};
